stages:
    - build_steam
    - build_standalone
    - check

variables:
    GIT_STRATEGY: clone
    QT_VERSION: 6.3.1
    PYTHON_VERSION: 3.10.1

build_standalone:windows:
    stage: build
    tags:
        - windows10
    script:
        - python -m pip install -U pip wheel
        - python -m pip install -U aqtinstall
        - python -m aqt install-qt -O ../aqt windows desktop $QT_VERSION win64_msvc2019_64 -m all
        - python -m aqt install-tool -O ../aqt windows desktop tools_ifw
        - cd Tools
        - python setup.py
        - python build.py -type release -use-aqt -installer -deploy
    artifacts:
        expire_in: "never"
        paths:
            - build-x64-windows-release/bin/
            - build-x64-windows-release/ScreenPlay-Installer.exe

build_standalone:osx:
    stage: build
    tags:
        - osx
    script:
        - pip3 install -U pip
        - pip3 install aqtinstall
        - python3 -m aqt install-qt -O ../aqt mac desktop $QT_VERSION clang_64 -m all
        - python3 -m aqt install-tool -O ../aqt mac desktop tools_ifw
        - cd Tools
        - python3 setup.py
        - python3 build.py -type release -use-aqt -deploy -architecture x64
        - python3 build.py -type release -use-aqt -deploy -architecture arm64
        - python3 macos_lipo.py
    artifacts:
        expire_in: "never"
        paths:
            - build-universal-osx-release/bin/

build_steam:windows:
    stage: build
    tags:
        - windows10
    script:
        - python -m pip install -U pip wheel
        - python -m pip install -U aqtinstall
        - python -m aqt install-qt -O ../aqt windows desktop $QT_VERSION win64_msvc2019_64 -m all
        - python -m aqt install-tool -O ../aqt windows desktop tools_ifw
        - cd Tools
        - python setup.py
        - python build.py -type release -steam -use-aqt -deploy
    artifacts:
        expire_in: "never"
        paths:
            - build-x64-windows-release/bin/

build_steam:osx:
    stage: build
    tags:
        - osx
    script:
        - pip3 install -U pip
        - pip3 install aqtinstall
        - python3 -m aqt install-qt -O ../aqt mac desktop $QT_VERSION clang_64 -m all
        - python3 -m aqt install-tool -O ../aqt mac desktop tools_ifw
        - cd Tools
        - python3 setup.py
        - python3 build.py -type release -steam -use-aqt -deploy -architecture x64
        - python3 build.py -type release -steam -use-aqt -deploy -architecture arm64
        - python3 macos_lipo.py
    artifacts:
        expire_in: "4 weeks"
        paths:
            - build-universal-osx-release/bin/

check:
    stage: check
    allow_failure: true
    image:
        name: ubuntu:20.04
    tags:
        - gitlab-org-docker
    before_script:
        - apt-get update -y
        - apt-get install python3-pip python-is-python3 -y
    script:
        - python -m pip install -U pip wheel
        - python -m pip install -U cmakelang
        - cd ./Tools
        - python clang_format.py
        - python cmake_format.py

build_docs:
    stage: .post
    script:
        - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.com/api/v4/projects/15800262/trigger/pipeline
