include:
    - ".gitlab/ci/base_jobs.yml"
    - ".gitlab/ci/build_jobs.yml"
    - ".gitlab/ci/build_release_jobs.yml"
    - ".gitlab/ci/check_jobs.yml"

stages:
    # Regular build for every commit
    - build
    # Git release tag builds
    - release_build
    # Checks for source code formattings
    - check

documentation:
    stage: .post
    script:
        - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.com/api/v4/projects/15800262/trigger/pipeline
