[project]
name = "screenplay-tools"
version = "0.1.0"
description = "ScreenPlay build and development tools"
requires-python = ">=3.10"
dependencies = [
    "cmake-format",
    "aqtinstall", 
    "requests",
    "setuptools",  # distutils
    "termcolor",
    "rich",
]

[tool.uv]
package = false

[tool.uv.sources]
# Use git, because the releases are quite old
aqtinstall = { git = "https://github.com/miurahr/aqtinstall.git", branch = "master" }
