// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: container.proto

#ifndef PROTOBUF_INCLUDED_container_2eproto
#define PROTOBUF_INCLUDED_container_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/any.pb.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_container_2eproto 

namespace protobuf_container_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_container_2eproto
namespace aimber {
class MessageContainer;
class MessageContainerDefaultTypeInternal;
extern MessageContainerDefaultTypeInternal _MessageContainer_default_instance_;
}  // namespace aimber
namespace google {
namespace protobuf {
template<> ::aimber::MessageContainer* Arena::CreateMaybeMessage<::aimber::MessageContainer>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace aimber {

// ===================================================================

class MessageContainer : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:aimber.MessageContainer) */ {
 public:
  MessageContainer();
  virtual ~MessageContainer();

  MessageContainer(const MessageContainer& from);

  inline MessageContainer& operator=(const MessageContainer& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MessageContainer(MessageContainer&& from) noexcept
    : MessageContainer() {
    *this = ::std::move(from);
  }

  inline MessageContainer& operator=(MessageContainer&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageContainer& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MessageContainer* internal_default_instance() {
    return reinterpret_cast<const MessageContainer*>(
               &_MessageContainer_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(MessageContainer* other);
  friend void swap(MessageContainer& a, MessageContainer& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MessageContainer* New() const final {
    return CreateMaybeMessage<MessageContainer>(NULL);
  }

  MessageContainer* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MessageContainer>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MessageContainer& from);
  void MergeFrom(const MessageContainer& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MessageContainer* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .google.protobuf.Any message = 1;
  int message_size() const;
  void clear_message();
  static const int kMessageFieldNumber = 1;
  ::google::protobuf::Any* mutable_message(int index);
  ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >*
      mutable_message();
  const ::google::protobuf::Any& message(int index) const;
  ::google::protobuf::Any* add_message();
  const ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >&
      message() const;

  // @@protoc_insertion_point(class_scope:aimber.MessageContainer)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any > message_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_container_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MessageContainer

// repeated .google.protobuf.Any message = 1;
inline int MessageContainer::message_size() const {
  return message_.size();
}
inline ::google::protobuf::Any* MessageContainer::mutable_message(int index) {
  // @@protoc_insertion_point(field_mutable:aimber.MessageContainer.message)
  return message_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >*
MessageContainer::mutable_message() {
  // @@protoc_insertion_point(field_mutable_list:aimber.MessageContainer.message)
  return &message_;
}
inline const ::google::protobuf::Any& MessageContainer::message(int index) const {
  // @@protoc_insertion_point(field_get:aimber.MessageContainer.message)
  return message_.Get(index);
}
inline ::google::protobuf::Any* MessageContainer::add_message() {
  // @@protoc_insertion_point(field_add:aimber.MessageContainer.message)
  return message_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >&
MessageContainer::message() const {
  // @@protoc_insertion_point(field_list:aimber.MessageContainer.message)
  return message_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace aimber

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_container_2eproto
