// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: container.proto

#ifndef PROTOBUF_container_2eproto__INCLUDED
#define PROTOBUF_container_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/any.pb.h>
// @@protoc_insertion_point(includes)
namespace community {
class MessageContainer;
class MessageContainerDefaultTypeInternal;
extern MessageContainerDefaultTypeInternal _MessageContainer_default_instance_;
}  // namespace community

namespace community {

namespace protobuf_container_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_container_2eproto

// ===================================================================

class MessageContainer : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:community.MessageContainer) */ {
 public:
  MessageContainer();
  virtual ~MessageContainer();

  MessageContainer(const MessageContainer& from);

  inline MessageContainer& operator=(const MessageContainer& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MessageContainer(MessageContainer&& from) noexcept
    : MessageContainer() {
    *this = ::std::move(from);
  }

  inline MessageContainer& operator=(MessageContainer&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageContainer& default_instance();

  static inline const MessageContainer* internal_default_instance() {
    return reinterpret_cast<const MessageContainer*>(
               &_MessageContainer_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(MessageContainer* other);
  friend void swap(MessageContainer& a, MessageContainer& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MessageContainer* New() const PROTOBUF_FINAL { return New(NULL); }

  MessageContainer* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MessageContainer& from);
  void MergeFrom(const MessageContainer& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MessageContainer* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .google.protobuf.Any message = 1;
  int message_size() const;
  void clear_message();
  static const int kMessageFieldNumber = 1;
  const ::google::protobuf::Any& message(int index) const;
  ::google::protobuf::Any* mutable_message(int index);
  ::google::protobuf::Any* add_message();
  ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >*
      mutable_message();
  const ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >&
      message() const;

  // @@protoc_insertion_point(class_scope:community.MessageContainer)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any > message_;
  mutable int _cached_size_;
  friend struct protobuf_container_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MessageContainer

// repeated .google.protobuf.Any message = 1;
inline int MessageContainer::message_size() const {
  return message_.size();
}
inline void MessageContainer::clear_message() {
  message_.Clear();
}
inline const ::google::protobuf::Any& MessageContainer::message(int index) const {
  // @@protoc_insertion_point(field_get:community.MessageContainer.message)
  return message_.Get(index);
}
inline ::google::protobuf::Any* MessageContainer::mutable_message(int index) {
  // @@protoc_insertion_point(field_mutable:community.MessageContainer.message)
  return message_.Mutable(index);
}
inline ::google::protobuf::Any* MessageContainer::add_message() {
  // @@protoc_insertion_point(field_add:community.MessageContainer.message)
  return message_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >*
MessageContainer::mutable_message() {
  // @@protoc_insertion_point(field_mutable_list:community.MessageContainer.message)
  return &message_;
}
inline const ::google::protobuf::RepeatedPtrField< ::google::protobuf::Any >&
MessageContainer::message() const {
  // @@protoc_insertion_point(field_list:community.MessageContainer.message)
  return message_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace community

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_container_2eproto__INCLUDED
